export const projects = [
  {
    id: 1,
    title: 'Identidade Visual - TechCorp',
    category: 'Design',
    description: 'Redesign completo da marca e manual de identidade.',
    image: 'https://picsum.photos/seed/techcorp/800/600',
    slug: 'techcorp',
    color: 'roxo',
    client: 'TechCorp Solutions',
    year: '2024',
    services: 'Branding, Papelaria, UI Design',
    heroImage: 'https://picsum.photos/seed/techcorp-hero/1920/1080',
    gallery: [
      'https://picsum.photos/seed/techcorp-1/800/600',
      'https://picsum.photos/seed/techcorp-2/800/600',
      'https://picsum.photos/seed/techcorp-3/800/600',
      'https://picsum.photos/seed/techcorp-4/800/600',
    ],
    about: 'A TechCorp nos procurou com o desafio de modernizar sua marca após 10 anos no mercado. O objetivo era transmitir inovação, segurança e agilidade, sem perder a essência corporativa.',
    challenge: 'O principal desafio foi criar uma identidade que funcionasse tanto no ambiente digital (aplicativos, site) quanto no físico (crachás, uniformes, papelaria), mantendo a consistência.',
    solution: 'Desenvolvemos um logotipo minimalista, uma paleta de cores vibrante baseada em tons de roxo e azul, e uma tipografia moderna. O manual da marca detalha todas as aplicações.',
    result: 'A nova identidade foi muito bem recebida pelos colaboradores e clientes, aumentando a percepção de valor da marca no mercado de tecnologia.',
    tags: ['Illustrator', 'Figma', 'Photoshop', 'InDesign'],
  },
  {
    id: 2,
    title: 'E-commerce - Moda Viva',
    category: 'Digital',
    description: 'Loja virtual de alta performance com integração ERP.',
    image: 'https://picsum.photos/seed/modaviva/800/600',
    slug: 'moda-viva',
    color: 'azul',
    client: 'Moda Viva',
    year: '2025',
    services: 'E-commerce, UX/UI, Integração',
    heroImage: 'https://picsum.photos/seed/modaviva-hero/1920/1080',
    gallery: [
      'https://picsum.photos/seed/modaviva-1/800/600',
      'https://picsum.photos/seed/modaviva-2/800/600',
      'https://picsum.photos/seed/modaviva-3/800/600',
      'https://picsum.photos/seed/modaviva-4/800/600',
    ],
    about: 'A Moda Viva precisava de um e-commerce robusto para expandir suas vendas online e integrar com seu sistema de gestão (ERP).',
    challenge: 'Criar uma experiência de compra fluida e rápida, lidando com um grande catálogo de produtos e picos de tráfego.',
    solution: 'Desenvolvemos uma loja virtual utilizando Next.js e Shopify, garantindo alta performance e SEO otimizado. A integração com o ERP foi feita via API.',
    result: 'Aumento de 150% nas vendas online no primeiro trimestre e redução de 40% no tempo de carregamento das páginas.',
    tags: ['Next.js', 'React', 'Shopify', 'Tailwind CSS'],
  },
  {
    id: 3,
    title: 'Embalagens - Café Premium',
    category: 'Gráfica',
    description: 'Design e impressão de embalagens sustentáveis.',
    image: 'https://picsum.photos/seed/cafe/800/600',
    slug: 'cafe-premium',
    color: 'teal',
    client: 'Café Premium',
    year: '2023',
    services: 'Design de Embalagem, Impressão',
    heroImage: 'https://picsum.photos/seed/cafe-hero/1920/1080',
    gallery: [
      'https://picsum.photos/seed/cafe-1/800/600',
      'https://picsum.photos/seed/cafe-2/800/600',
      'https://picsum.photos/seed/cafe-3/800/600',
      'https://picsum.photos/seed/cafe-4/800/600',
    ],
    about: 'O Café Premium lançou uma nova linha de cafés especiais e precisava de embalagens que refletissem a qualidade do produto e o compromisso com a sustentabilidade.',
    challenge: 'Desenvolver um design atraente que se destacasse nas prateleiras e utilizar materiais ecológicos para a impressão.',
    solution: 'Criamos um design minimalista com ilustrações botânicas e utilizamos papel kraft reciclado com impressão em tintas ecológicas.',
    result: 'As novas embalagens ganharam um prêmio de design sustentável e ajudaram a marca a entrar em novas redes de supermercados.',
    tags: ['Illustrator', 'Design Gráfico', 'Produção Gráfica'],
  },
  {
    id: 4,
    title: 'App Mobile - FitTrack',
    category: 'Digital',
    description: 'Interface UI/UX para aplicativo de saúde e fitness.',
    image: 'https://picsum.photos/seed/fittrack/800/600',
    slug: 'fittrack',
    color: 'azul',
    client: 'FitTrack Inc.',
    year: '2024',
    services: 'UI/UX Design, Prototipagem',
    heroImage: 'https://picsum.photos/seed/fittrack-hero/1920/1080',
    gallery: [
      'https://picsum.photos/seed/fittrack-1/800/600',
      'https://picsum.photos/seed/fittrack-2/800/600',
      'https://picsum.photos/seed/fittrack-3/800/600',
      'https://picsum.photos/seed/fittrack-4/800/600',
    ],
    about: 'A FitTrack nos contratou para redesenhar a interface do seu aplicativo de monitoramento de atividades físicas, visando melhorar a retenção de usuários.',
    challenge: 'Simplificar a navegação complexa do aplicativo antigo e criar um visual mais moderno e motivador.',
    solution: 'Realizamos pesquisas com usuários, criamos wireframes e desenvolvemos um protótipo de alta fidelidade no Figma, focando em gamificação e clareza de dados.',
    result: 'O novo design aumentou o engajamento diário dos usuários em 35% e recebeu avaliações positivas nas lojas de aplicativos.',
    tags: ['Figma', 'UX Research', 'Prototipagem'],
  },
  {
    id: 5,
    title: 'Campanha - Verão 2025',
    category: 'Design',
    description: 'Direção de arte e peças para redes sociais.',
    image: 'https://picsum.photos/seed/verao/800/600',
    slug: 'campanha-verao',
    color: 'roxo',
    client: 'Marca de Moda Praia',
    year: '2024',
    services: 'Direção de Arte, Social Media',
    heroImage: 'https://picsum.photos/seed/verao-hero/1920/1080',
    gallery: [
      'https://picsum.photos/seed/verao-1/800/600',
      'https://picsum.photos/seed/verao-2/800/600',
      'https://picsum.photos/seed/verao-3/800/600',
      'https://picsum.photos/seed/verao-4/800/600',
    ],
    about: 'Criação da identidade visual e peças de comunicação para a campanha de lançamento da coleção de verão 2025 de uma marca de moda praia.',
    challenge: 'Transmitir a energia e as cores do verão de forma vibrante e atraente para o público jovem.',
    solution: 'Desenvolvemos um conceito visual baseado em cores quentes, tipografia ousada e colagens digitais, aplicadas em posts, stories e banners.',
    result: 'A campanha gerou um alto nível de engajamento nas redes sociais e contribuiu para o esgotamento de várias peças da coleção na primeira semana.',
    tags: ['Photoshop', 'Illustrator', 'Direção de Arte'],
  },
  {
    id: 6,
    title: 'Papelaria - Advogados Associados',
    category: 'Gráfica',
    description: 'Cartões de visita com hot stamping e papel texturizado.',
    image: 'https://picsum.photos/seed/advogados/800/600',
    slug: 'advogados',
    color: 'teal',
    client: 'Escritório de Advocacia',
    year: '2023',
    services: 'Design de Papelaria, Impressão Premium',
    heroImage: 'https://picsum.photos/seed/advogados-hero/1920/1080',
    gallery: [
      'https://picsum.photos/seed/advogados-1/800/600',
      'https://picsum.photos/seed/advogados-2/800/600',
      'https://picsum.photos/seed/advogados-3/800/600',
      'https://picsum.photos/seed/advogados-4/800/600',
    ],
    about: 'Um escritório de advocacia tradicional buscou nossos serviços para renovar sua papelaria institucional, buscando um visual mais sofisticado.',
    challenge: 'Criar materiais que transmitissem credibilidade e elegância, utilizando acabamentos gráficos especiais.',
    solution: 'Desenhamos cartões de visita, pastas e envelopes com um design sóbrio, utilizando papel texturizado de alta gramatura e aplicação de hot stamping dourado no logotipo.',
    result: 'A nova papelaria elevou a percepção da marca pelos clientes do escritório, transmitindo profissionalismo e atenção aos detalhes.',
    tags: ['InDesign', 'Produção Gráfica', 'Acabamentos Especiais'],
  },
  {
    id: 7,
    title: 'Site Institucional - Construtora',
    category: 'Digital',
    description: 'Site responsivo com portfólio de obras e blog.',
    image: 'https://picsum.photos/seed/construtora/800/600',
    slug: 'construtora',
    color: 'azul',
    client: 'Construtora Horizonte',
    year: '2024',
    services: 'Web Design, Desenvolvimento Web',
    heroImage: 'https://picsum.photos/seed/construtora-hero/1920/1080',
    gallery: [
      'https://picsum.photos/seed/construtora-1/800/600',
      'https://picsum.photos/seed/construtora-2/800/600',
      'https://picsum.photos/seed/construtora-3/800/600',
      'https://picsum.photos/seed/construtora-4/800/600',
    ],
    about: 'Desenvolvimento do novo site institucional da Construtora Horizonte para apresentar seu portfólio de obras e captar novos clientes.',
    challenge: 'Criar um site moderno, rápido e fácil de atualizar, com uma galeria de imagens otimizada para mostrar os detalhes dos projetos.',
    solution: 'Utilizamos Next.js e um CMS headless para facilitar a gestão de conteúdo. O design foca em imagens grandes e navegação intuitiva.',
    result: 'O novo site melhorou o posicionamento da construtora no Google (SEO) e aumentou o número de contatos qualificados recebidos pelo formulário.',
    tags: ['Next.js', 'Tailwind CSS', 'CMS', 'SEO'],
  },
  {
    id: 8,
    title: 'Banners - Evento Tech',
    category: 'Gráfica',
    description: 'Comunicação visual para evento de tecnologia.',
    image: 'https://picsum.photos/seed/evento/800/600',
    slug: 'evento-tech',
    color: 'teal',
    client: 'Tech Summit 2024',
    year: '2024',
    services: 'Sinalização, Impressão em Grandes Formatos',
    heroImage: 'https://picsum.photos/seed/evento-hero/1920/1080',
    gallery: [
      'https://picsum.photos/seed/evento-1/800/600',
      'https://picsum.photos/seed/evento-2/800/600',
      'https://picsum.photos/seed/evento-3/800/600',
      'https://picsum.photos/seed/evento-4/800/600',
    ],
    about: 'Produção de toda a comunicação visual impressa para um grande evento de tecnologia, incluindo banners, backdrops, credenciais e sinalização direcional.',
    challenge: 'Garantir a qualidade de impressão em grandes formatos e cumprir um prazo de entrega muito apertado.',
    solution: 'Trabalhamos em estreita colaboração com a equipe do evento para aprovar os arquivos rapidamente e coordenamos a produção com nossa gráfica parceira de alta capacidade.',
    result: 'Todo o material foi entregue no prazo e com excelente qualidade, contribuindo para o sucesso e a organização visual do evento.',
    tags: ['Illustrator', 'Grandes Formatos', 'Gestão de Produção'],
  },
  {
    id: 9,
    title: 'Social Media - Restaurante',
    category: 'Design',
    description: 'Gestão de redes sociais e criação de conteúdo.',
    image: 'https://picsum.photos/seed/restaurante/800/600',
    slug: 'restaurante',
    color: 'roxo',
    client: 'Bistrô Sabor',
    year: '2023',
    services: 'Design para Redes Sociais, Fotografia',
    heroImage: 'https://picsum.photos/seed/restaurante-hero/1920/1080',
    gallery: [
      'https://picsum.photos/seed/restaurante-1/800/600',
      'https://picsum.photos/seed/restaurante-2/800/600',
      'https://picsum.photos/seed/restaurante-3/800/600',
      'https://picsum.photos/seed/restaurante-4/800/600',
    ],
    about: 'Criação de conteúdo visual para as redes sociais de um restaurante local, com o objetivo de atrair novos clientes e aumentar as reservas.',
    challenge: 'Produzir fotos apetitosas dos pratos e criar um feed harmonioso e atrativo no Instagram.',
    solution: 'Realizamos sessões de fotos profissionais dos pratos e criamos templates de design para os posts, mantendo uma identidade visual consistente.',
    result: 'O perfil do restaurante ganhou milhares de novos seguidores e as reservas online aumentaram significativamente.',
    tags: ['Fotografia', 'Photoshop', 'Social Media Design'],
  },
];
