// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ijuiifffwwilninyxobb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqdWlpZmZmd3dpbG5pbnl4b2JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4MTEwNTAsImV4cCI6MjA5MDM4NzA1MH0.eADmmatldttFnaeXm-N1fkN3KAt-GXoFguqyWKC5W4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);